services:
  backend-sandbox:
    image: antivariant/backend-sandbox:${BACKEND_SANDBOX_IMAGE_TAG:-dev}
    ports:
      - "3000:3000"
    env_file:
      - ${BACKEND_SANDBOX_ENV_FILE:-./backend-sandbox/.env.prod}
    networks:
      - app-net

  backend-sdet:
    image: antivariant/backend-sdet:${BACKEND_SDET_IMAGE_TAG:-dev}
    ports:
      - "3100:3100"
    env_file:
      - ${BACKEND_SDET_ENV_FILE:-./backend-sdet/.env.prod}
    networks:
      - app-net

  frontend-web:
    image: antivariant/frontend-web:${FRONTEND_WEB_IMAGE_TAG:-dev}
    ports:
      - "3030:3030"
    env_file:
      - ${FRONTEND_WEB_ENV_FILE:-./frontend-web/.env.production}
    environment:
      - NEXT_PUBLIC_API_TARGET=docker
    networks:
      - app-net

  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    env_file:
      - ${NGINX_ENV_FILE:-./frontend-web/.env.production}
    volumes:
      - ./nginx/templates:/etc/nginx/templates:ro
      - nginx-cache:/var/cache/nginx
    depends_on:
      - backend-sandbox
      - backend-sdet
    networks:
      - app-net

networks:
  app-net:
    driver: bridge

volumes:
  nginx-cache:
